# Generated by Django 4.1.2 on 2024-06-30 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('ranking', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=300)),
                ('anio', models.IntegerField(max_length=20)),
                ('calificacion', models.IntegerField(max_length=20)),
                ('image', models.CharField(max_length=300)),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='pelis.genero')),
            ],
        ),
    ]
