# Generated by Django 4.1.2 on 2024-06-30 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Peliculas',
        ),
    ]
