# Generated by Django 4.1.2 on 2024-07-01 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0002_rename_alumno_peliculas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id_musica', models.AutoField(db_column='idMusica', primary_key=True, serialize=False)),
                ('tipo_musica', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='anio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='calificacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='ranking',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=70)),
                ('artista', models.CharField(max_length=70)),
                ('anio', models.IntegerField()),
                ('image', models.CharField(max_length=300)),
                ('id_musica', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='pelis.musica')),
            ],
        ),
    ]
