# Generated by Django 4.1.2 on 2024-07-01 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0003_musica_alter_peliculas_anio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cancion',
        ),
    ]
