# Generated by Django 4.1.2 on 2024-07-01 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0004_delete_cancion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=70)),
                ('artista', models.CharField(max_length=70)),
                ('anio', models.IntegerField()),
                ('duracion', models.CharField(max_length=70)),
                ('image', models.CharField(max_length=300)),
                ('id_musica', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='pelis.musica')),
            ],
        ),
    ]
