# Generated by Django 4.1.2 on 2024-06-03 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id_ramo', models.AutoField(db_column='idRamo', primary_key=True, serialize=False)),
                ('ramo', models.CharField(max_length=20)),
                ('creditos', models.IntegerField()),
                ('escuela', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.AutoField(db_column='idSeccion', primary_key=True, serialize=False)),
                ('seccion', models.CharField(max_length=20)),
                ('cupos', models.IntegerField()),
                ('horario', models.CharField(max_length=45)),
                ('id_ramo', models.ForeignKey(db_column='idRamo', null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.ramo')),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alumno', models.ForeignKey(db_column='nombre', on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('id_seccion', models.ForeignKey(db_column='idSeccion', on_delete=django.db.models.deletion.CASCADE, to='alumnos.seccion')),
            ],
        ),
    ]
